

# 问题

## concurrency?
可能是缺少await导致同时访问dbContext




## 异常处理


### async Task
不等待该类型方法，会变成Task异常。
Task异常仅在Task资源被GC后触发事件。

### async void
该类型方法不进行Try Catch， 会变成Unhandled Exception异常，直接Crash掉应用！

```cs
 public override async Task DoWorkAsync(CancellationToken cancellationToken = default)
 {
     try
     {
         
         TestAsyncVoid();
     }
     catch (Exception ex)
     {
         Console.WriteLine();
     }
 }

 public async void TestAsyncVoid() //去掉async即解决！
 {
     throw new Exception("测试");
 }

```
